# Generated by Django 4.1.2 on 2022-10-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="desc",
            new_name="feedback",
        ),
    ]
